version: "3.9"

services:
  miknas:
    image: miknas
    user: "1000:1000"
    ports:
      - "2021:2020"
    volumes:
      - ../../test/webroot:/web
    restart: always
    environment:
      MIKNAS_ADMIN_UID: admin